{
 "title": "Workspace Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "cpu_core_num",
    "label": "Core",
    "query": {
     "query": "SELECT DISTINCT core_num FROM cpu"
    }
   },
   {
    "name": "batery_count",
    "label": "battery",
    "query": {
     "query": "SELECT DISTINCT battery_index FROM battery"
    }
   },
   {
    "name": "disk_name",
    "label": "disk",
    "query": {
     "query": "SELECT DISTINCT disk_name FROM disk"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage Per Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  date_bin(\r\n    INTERVAL '5 seconds',\r\n    \"time\",\r\n    TIMESTAMP '1970-01-01T00:00:00Z'\r\n  ) AS \"time\",\r\n  CONCAT('Core ', LPAD(CAST(\"core_num\" AS VARCHAR), 2, '0')) AS \"core\",\r\n  AVG(\"percent_usage\") AS \"value\"\r\nFROM \"cpu\"\r\nWHERE\r\n  \"time\" >= $__timeFrom\r\n  AND \"time\" <= $__timeTo\r\n  AND \"core_num\" IN (${cpu_core_num:csv})\r\nGROUP BY 1, 2\r\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Average CPU Usage (All cores)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT AVG(\"percent_usage\") FROM \"cpu\" WHERE \"time\" >= NOW() - INTERVAL '5 SECOND'"
    }
   ]
  },
  {
   "title": "Average CPU Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT AVG(\"percent_usage\"), \"time\" FROM \"cpu\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo GROUP BY \"time\" "
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "Ram Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"percent_usage\", \"time\" FROM \"ram\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"percent_usage\" FROM \"ram\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Total Disk Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"GB_usage\" FROM \"disk\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"percent_usage\", \"time\" FROM \"disk\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"percent_usage\" FROM \"disk\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Battery Percentage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"percent_charge\", \"time\" FROM \"battery\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Battery Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"battery_status\", \"time\" FROM \"battery\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Battery Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 39 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  date_bin(\r\n    INTERVAL '5 seconds',\r\n    \"time\",\r\n    TIMESTAMP '1970-01-01T00:00:00Z'\r\n  ) AS \"time\",\r\n  CONCAT('Battery ', LPAD(CAST(\"battery_index\" AS VARCHAR), 2, '0')) AS \"battery\",\r\n  AVG(\"percent_charge\") AS \"value\"\r\nFROM \"battery\"\r\nWHERE\r\n  \"time\" >= $__timeFrom\r\n  AND \"time\" <= $__timeTo\r\n  AND \"battery_index\" IN (${batery_count:csv})\r\nGROUP BY 1, 2\r\nORDER BY 1, 2;"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Network - Bytes Received/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin(\n    INTERVAL '5 seconds',\n    \"time\",\n    TIMESTAMP '1970-01-01T00:00:00Z'\n  ) AS \"time\",\n  \"adapter_name\",\n  AVG(\"bytes_received_per_sec\") AS \"value\"\nFROM \"network\"\nWHERE\n  \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nGROUP BY 1, 2\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Network - Bytes Sent/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin(\n    INTERVAL '5 seconds',\n    \"time\",\n    TIMESTAMP '1970-01-01T00:00:00Z'\n  ) AS \"time\",\n  \"adapter_name\",\n  AVG(\"bytes_sent_per_sec\") AS \"value\"\nFROM \"network\"\nWHERE\n  \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nGROUP BY 1, 2\nORDER BY 1, 2;"
    }
   ]
  }
 ]
}